Add og tags for facebook
cortlandtlabs/cortlandtlabs.github.io pull request #20
Opened 2016-09-28 13:26 UTC by jhack32

https://blog.kissmetrics.com/open-graph-meta-tags/

2016-09-28 14:08 UTC, dijonkitchen requested changes
Cool stuff! See my comments. Did you also check it on Facebook's crawler to test it? https://developers.facebook.com/docs/sharing/webmasters

Do we also want to add Twitter stuff while we're at it?

2016-09-28 14:08 UTC, dijonkitchen commented on index.html
> +  <meta property="og:description" content="Cortlandt Labs is a technology consulting agency started in NYC."
Missing self-closing tag.

2016-09-28 14:08 UTC, dijonkitchen commented on index.html
> +  <meta property="og:image" content="https://raw.githubusercontent.com/cortlandtlabs/cortlandtlabs.github.io/master/assets/Cortlandt-Labs-logo.png"/>
Can we use a relative link here?

2016-09-28 14:08 UTC, dijonkitchen commented on index.html
> +  <meta property="og:locale" content="en_US" />
Perhaps group all these meta tags on the top with the other meta tags and add a line comment for Facebook Open Graph?

2016-09-29 12:36 UTC, jhack32 reviewed
Changes were made based on comments. I don't think we need to add twitter tags because if twitter tags can't be located, it will look at the og tags.

2016-09-29 12:36 UTC, jhack32 commented on index.html
> +  <meta property="og:image" content="https://raw.githubusercontent.com/cortlandtlabs/cortlandtlabs.github.io/master/assets/Cortlandt-Labs-logo.png"/>
I don't think so

2016-09-29 12:40 UTC, dijonkitchen approved these changes

2016-09-29 12:43 UTC, dijonkitchen commented on index.html
> +  <meta property="og:image" content="https://raw.githubusercontent.com/cortlandtlabs/cortlandtlabs.github.io/master/assets/Cortlandt-Labs-logo.png"/>
I'll look into it later, but the absolute link should work fine for now.

2016-09-29 12:44 UTC, dijonkitchen commented
👍 Love the new review system!

2016-09-30 02:47 UTC, aattsai approved these changes

2016-09-30 02:47 UTC, merged