Add meta tag for description to adjust google description
cortlandtlabs/cortlandtlabs.github.io pull request #29
Opened 2016-09-30 18:44 UTC by jhack32

Any suggestions on what the description should be? I just combined the facebook about and some of the text on the website.

2016-09-30 19:00 UTC, dijonkitchen requested changes
Add a period at end, but that's good for now. 

Can you see how it looks in the validators that Facebook, Google, and Twitter have?

2016-10-01 16:32 UTC, jhack32 commented
It should be good now, but for the facebook image, should we use the NYC WTC image instead of our logo?

2016-10-01 16:39 UTC, aattsai commented
But WTC is already the cover photo

2016-10-01 17:32 UTC, dijonkitchen commented on index.html
> +  <meta property="og:image" content="http://cortlandtlabs.co/assets/Cortlandt-Labs-logo.png"/>
Still think /assets/ works.

2016-10-01 17:32 UTC, dijonkitchen approved these changes

2016-10-01 17:33 UTC, dijonkitchen commented
I'm not sure how it looks, but our logo should be good.

2016-10-01 17:35 UTC, merged

2016-10-01 17:41 UTC, jhack32 commented
Facebook's example shows og:image using a http link, and the other examples I've seen are using HTTP links. I think open graph takes the content exactly as is and if we use a static link, it will just be going to '/assets/cortlandt-labs-logo.png' rather than 'http://cortlandtlabs.co/assets/cortlandt-labs-logo.png'