Contact
cortlandtlabs/cortlandtlabs.github.io pull request #37
Opened 2016-11-12 23:12 UTC by jhack32

Fixes Issue # .

Changes proposed in this pull request:

2016-11-13 10:26 UTC, dijonkitchen commented
It makes sense to me!

2016-11-13 21:42 UTC, aattsai approved these changes

2016-11-14 14:56 UTC, dijonkitchen commented on contact.html
> +      <input type="text" name="_gotcha" style="display:none" />
What's this do?

2016-11-14 14:58 UTC, jhack32 commented on contact.html
> +      <input type="text" name="_gotcha" style="display:none" />
Avoid spambots

2016-11-14 15:16 UTC, dijonkitchen requested changes
Let's add some of the other FormSpree advanced options like:

Reply to email, so we have their email and can respond quickly. There's no guarantee currently that they'll provide a contact number/email. 

Use _next to redirect to our page instead of FormSpree.

Default a subject so we can filter our email by email we get from the website.

2016-11-14 18:23 UTC, dijonkitchen requested changes

2016-11-14 18:23 UTC, dijonkitchen commented on contact.html
> +        <input type="text" name="email" placeholder="E-mail" required />
Use "email" as the type for form validation: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

2016-11-14 18:23 UTC, dijonkitchen commented on contact.html
> +        <input type="text" name="_subject" placeholder="Subject" required />
Do we want custom subjects for should we have a few options for them in a drop-down?

2016-11-14 18:23 UTC, dijonkitchen commented on contact.html
> +        <input type="text" name="name" placeholder="Name" required />
Do we need to require their name? We can keep the form simpler without it or make it optional.

2016-12-11 16:44 UTC, dijonkitchen commented
Bump

2016-12-13 02:10 UTC, jhack32 commented on contact.html
> +        <input type="text" name="name" placeholder="Name" required />
Yeah, I think we should have a required name. Let's us know who it's from

2016-12-13 02:12 UTC, jhack32 commented on contact.html
> +        <input type="text" name="_subject" placeholder="Subject" required />
I think it's okay to have custom subjects

2016-12-13 02:14 UTC, aattsai approved these changes

2016-12-13 02:36 UTC, dijonkitchen approved these changes

2016-12-13 02:36 UTC, merged